### ISSUE TITLE
Conformal

### ISSUE THREAD

**Issue by firmai** [tblume1992/MFLES#1]
Thanks again for a nice package, it would be great if we can weave conformal prediction into this function and they can be returned as columns.

```
from MFLES.Forecaster import fit_from_df

output = fit_from_df(df_signal,
                      forecast_horizon=210,
                      freq='W',
                      seasonal_period=[13, 26, 52, 104,210,420, 840],
                      id_column='ticker',
                      time_column='date',
                      value_column='total_revenue',
                      floor=0)
```

**Comment by tblume1992** [comment]
@firmai I totally agree! Should not be tough, I'll add it.

**Comment by tblume1992** [comment]
@firmai I was not ignoring this request! Nixtla just released MFLES as part of their statsforecast library which enables this feature and should be the go-to for MFLES forecasting. I will keep this package around more for experimentation.
https://github.com/Nixtla/statsforecast
